### ISSUE TITLE
code generator to add database definitions to the sdk

### ISSUE THREAD

**Issue by marcomow** [apitable/apitable-sdks#95]
Hi, I've stumbled across Apitable only today, and felt in love: it's a real Airtable competitor...on steroids! 

Lately I was playing with NocoDB - but hosting yourself it's a hassle and may become expensive - and Xata, that's not very developed on user friendly interface.
At the same time Xata has this really cool code generator (that I was replicating for NocoDB using swagger.json automatically provided) https://xata.io/docs/cli/codegen .

It would be perfect for the Developer Experience to have something as such. Does Apitable provide a swagger.json file? I could build the code generator for TypeScript

**Comment by xukecheng** [comment]
Something went wrong in https://xata.io/docs/cli/codegen. The page was not found. Maybe you can directly use apitable.js.
