### ISSUE TITLE
fix: more clear error message in apitable.js

### ISSUE THREAD

**Issue by arucil** [apitable/apitable-sdks#97]
In https://github.com/apitable/apitable-sdks/blob/develop/apitable.js/lib/apitable.ts#L90 , the error thrown by axios is hidden, and a fake 500 error is reported to the user, which will confuse the user. The actual error should be reported to the user, or just thrown verbatim.

**Comment by csankhala** [comment]
As per current implementation,

```
result = {
        success: false,
        code: error?.code || 500,
        message: error?.message || 'Request parameter misconfiguration',
      };
```

It is checking actual error first. if not found then only it falls to default hardcoded result code and error message.
@arucil Can you please elaborate more on issue by giving example or screenshot.
Thanks

**Comment by arucil** [comment]
@csankhala One of our users has run into this problem recently. The reported error by JS SDK is `500 Request parameter misconfiguration`, however APITable will never report this error, which means the error caught by the try-block does not contain `code` and `message`, so it's hard for the user to track the original cause if the actual error is hidden and a meaningless error is reported instead.
